require_relative 'processor/main'
require_relative 'processor/else'
require_relative 'processor/empty_else'
require_relative 'processor/empty_if'
require_relative 'processor/if_else_builder'
require_relative 'processor/if'
require_relative 'processor/procedure_definition'
require_relative 'processor/times'
